General housekeeping
KTH/lms-sis-monitor pull request #20
Opened 2022-08-24 13:06 UTC by jhsware

Bumped some packages and:
- improved retry when canvas is unreachable
- added two apps to monitor
- removed deprecated app from list of apps to monitor
- fixed some prettier warnings

2022-08-25 13:49 UTC, exacs requested changes

2022-08-25 13:49 UTC, exacs commented on src/run-periodically.js
> +    return false;
I think with this new implementation, we should remove the entire `running` variable (defined in line 14)

According to the code below, the variable is never set to `false` and therefore this condition `if (running)` will be true always, which means that sync is executed only once!

2022-10-26 12:56 UTC, me97esn commented on src/run-periodically.js
> +      "lms-sync-users",
We should use this app to monitor as many of our apps as possible. But note that there will be a lot of false warnings/errors in some of them, so they should be added with caution and perhaps ignore some errors. Have you tested that adding `lms-sync-users` makes sense? If so: I agree that this is an improvement. But if it hasn't been properly tested yet, it should be done before merge and deploy.

2022-10-26 12:58 UTC, me97esn requested changes
See my note below about adding the new app `lms-sync-users`. This note should be taken into account before this PR is merged.

2022-10-26 13:21 UTC, jhsware commented on src/run-periodically.js
> +    return false;
I have totally missed this comment!

`running` is set to false on row 45 and 49 and initialised to false on row 14. If row 44 fails it will cause the app to stop working though.

2022-11-02 13:58 UTC, merged