Redesign
KTH/lms-sis-monitor pull request #7
Opened 2020-11-23 11:24 UTC by exacs

2020-11-24 15:21 UTC, me97esn commented
Did you leave node-schedule on purpose? Or did you just forget to replace it with setTimeout?

2020-11-24 15:27 UTC, me97esn commented on cron/index.js
> +  const oneDayBack = dateFns.subDays(new Date(), 1)
Is there a reason for using dateFns instead of something like `const oneDayBack = new Date()
oneDayBack.setDate( new Date().getDate()-1 )` ?

2020-11-25 08:06 UTC, me97esn commented on lib/parse-error.js
> +/** @return {SisError?} */
I'm usually not a huge proponent of the DRY (don't repeat yourself) principle, since it often contradicts the KISS (keep it simple and stupid) principle which is more important imo. But perhaps this is a good place to see if we can refactor? We have three functions containing the following lines of code:
`if (!err.message.startsWith(prefix)) {
    return
  }

  const suffix = err.message.slice(prefix.length)
`
Can we refactor so that we only define this logic once, _but still keep the code simple and stupid_?

2020-11-25 08:11 UTC, me97esn commented on lib/is-known-error.js
> +
We should really document why we do this. _I know why_, but for a newcomer this will look really confusing. We _should_ have a confluence page somewhere where this use case is documented, perhaps we should link to that page from the code comment? I'm not sure about the best way to document this, but I'm certain that we have to describe it in some way.

2020-11-25 08:28 UTC, me97esn commented on lib/is-known-error.js
> +
The use case is shortly documented here: https://confluence.sys.kth.se/confluence/pages/viewpage.action?pageId=47352006. But since it's hidden behind our login server, and isn't written from a technical perspective anyways, perhaps the best is to just add a few lines in a comment in this file?

2020-11-25 08:31 UTC, exacs commented
> Did you leave node-schedule on purpose? Or did you just forget to replace it with setTimeout?

Forgot to replace it 😅 Good catch!

2020-11-25 13:36 UTC, me97esn commented
I have just started testing this. I'm missing the most important information imo: _the id of the sis import_. I wan't to double check the uploaded csv file and see that the monitor parses the errors correctly.

2020-11-26 13:32 UTC, kaj requested changes
Since there is no cron involved any more, that directory should probably be renamed.  Also, it only contains one file, and I think it is always a good idea to rename a lonely `foo/index.js` to just `foo.js`.  So in this case, move `cron/index.js` to `periodic.js` ?

As for @me97esn s comment about maybe doing some more refactoring "in spite of" the KISS rule, I think that should probably be done _because_ of the KISS rule.  KISS is said to mean "Keep It Simple, Stupid", which sure is catchy, but a better interpretation is "Keep It Short (and) Simple".  The biggest readability problem in code is that there is just too much code to read.

2020-11-26 13:32 UTC, kaj commented on lib/parse-error-message.js
> +  const pattern1 = /Neither course nor section existed for user enrollment \(Course ID: (.+)?, Section ID: (.+)?, User ID: (.+)?\)/
I think these patterns (that are just numbered rather than named) are declared rather far from their use.  How should anyone know what a match4[2] is in the code below?

I think this could be written as

```js
return parseMissingSecton(message)
       || parseMissingUser(message)
    /* ... more or clauses, one for each pattern */
```

And a bunch of short private functions that parses / recognizes one pattern each.

2020-11-26 13:32 UTC, kaj commented on server/index.js
>    res.send('APPLICATION_STATUS: OK')
Huh?  Shouldn't this report what was actually found by all those parsers and counters?  Or at least check there peridoc job has actually executed recently?

2020-11-26 13:32 UTC, kaj commented on app.js
>  server.listen(3000)
Nothing actually cares about return values or errors from `cron` here, so if that is terminated by an exception or just hang, server just keeps on running.  And as long as the server is running, it will claim that all is well.

2020-11-26 14:32 UTC, me97esn commented on lib/parse-error-message.js
> +  const pattern1 = /Neither course nor section existed for user enrollment \(Course ID: (.+)?, Section ID: (.+)?, User ID: (.+)?\)/
Yes, that's a really good point. Perhaps we should fix it, but I've already merged this PR, so perhaps this should be a teknik-card. 
Worth noting is that I'm getting cold feet about this app, we're gonna have a meeting where we discuss it tomorrow. I fear that it will soon be our most complex application if we want to make sure that we handle every type of expected error message, or we will have lots of false alarms each morning.

2020-11-26 15:00 UTC, kaj commented on lib/parse-error-message.js
> +  const pattern1 = /Neither course nor section existed for user enrollment \(Course ID: (.+)?, Section ID: (.+)?, User ID: (.+)?\)/
> I've already merged this PR

Huh?  Then why does github think it's still open?

As for the complexity, a complex program is still _way_ better than a complex manual routine.  But we'll see what comes out of that meeting.

2020-12-02 12:17 UTC, closed without merging