Redesign2
KTH/lms-sis-monitor pull request #8
Opened 2020-12-02 12:34 UTC by exacs

Redesign and re-implementation of SIS Monitor. I have created a new PR because this one has a different design after a discussion we had on the strategy to monitor SIS Import Errors.

---

## Description of the strategy:

1. Every app that send files to Canvas will send them with the app name as filename prefix. For example, `lms-activity-rooms` will send files called `lms-activity-rooms_examinations` or something.
2. For now, this LMS SIS Monitor will only look at errors that happen on `lms-activity-rooms` because errors that came from that application will almost never be false positives.
3. Point number 2 is implemented but not point number 1. This means that **LMS SIS Monitor doesn't catch any errors yet but is ready to start catching them.**
4. Because of point number 2, I have decided to remove all checks of false-positive errors. It might come back in a future.

---

- The important file is [`src/log-errors.js`](https://github.com/KTH/lms-sis-monitor/blob/redesign2/src/log-errors.js) which contains the logic of monitoring errors
- This PR also includes other minor fixes like filename changes.

---

## 👀 Tips for testing this application

This application runs a periodical task. However, it is separated the "run a task periodically" and the "task itself" since the latter is more important to test.

There is a file called [`scripts/errors-last-hour`](https://github.com/KTH/lms-sis-monitor/blob/redesign2/scripts/errors-last-hour.js) that runs the task without the need of running the server.

2020-12-03 09:45 UTC, me97esn commented on src/log-errors.js
> +      if (imp.workflow_state !== 'imported') {
Can you add a comment here please? Why are these two if:s needed?

2020-12-03 09:49 UTC, me97esn requested changes
Just a minor change requested

2020-12-03 10:13 UTC, me97esn commented on app.js
> +const runPeriodically = require('./run-periodically')
Shouldn't this be ./src/run-periodically?

2020-12-03 10:15 UTC, me97esn requested changes
Have you tested this PR @exacs ? It crashes when I try to run it locally, because it tries to find ./run-periodically when it's actually in the `src` folder...
This is why I don't want to use a script like `errors-last-hour.js` when I test the code, but rather think you should run the actual app when testing it

2020-12-03 10:56 UTC, exacs reviewed
Good catch of the error @me97esn!! I'll keep in mind your comment! I think it is ok to have the `errors-last-hour` script anyways _after_ we are sure that the app runs

2020-12-03 10:56 UTC, exacs commented on src/log-errors.js
> +      if (imp.workflow_state !== 'imported') {
I thought to "return everything if `prefixes` is an empty array" but it's strange behavior actually.

Answer: the two ifs are not needed :)

2020-12-04 10:08 UTC, me97esn commented
When testing this I think we should make a minor change that makes it easier to debug the errors:
Since we might log the same error multiple times (for instance if we see an error, fix the underlying issue and then restart the lms-sis-monitor app), I think it would be really valuable information to log the _time_ of the sis import. That could make it obvious if this is a new error or something we already have fixed

2020-12-04 10:10 UTC, me97esn requested changes
See my comment under conversations: I would like us to log the time of the sis import in the error message

2020-12-07 09:09 UTC, merged